### ISSUE TITLE
Invalid undefined width of type string supplied to StyleSheet imagePlaceholder, expected number

### ISSUE THREAD

**Issue by trymbill** [dejakob/react-native-keyboard-aware-parallax-scroll-view#1]
I'm not sure why you are able to use % in your StyleSheet but on my end it throws ```Invalid undefined width of type string supplied to StyleSheet imagePlaceholder, expected number```.

Am I missing a dependency or need to update react native?

**Comment by trymbill** [comment]
Updated RN to 0.44.3 and 100% width works.

**Comment by dejakob** [comment]
I prefer using 100% over Dimensions.get('window').width because Dimensions won't change when you rotate the device. Indeed it's a pretty new feature.
